import type {
  CreationOptional,
  InferAttributes,
  InferCreationAttributes,
  NonAttribute,
} from 'sequelize';
import {
  BelongsTo,
  Column,
  CreatedAt,
  DataType,
  ForeignKey,
  Model,
  Table,
  UpdatedAt,
} from 'sequelize-typescript';
import { EVENT_STATUSES, type EventStatus } from '@garba-partner/shared';
import { AdminUser } from './admin-user.model.js';
import { Area } from './area.model.js';
import { City } from './city.model.js';
import { EventOrganizer } from './event-organizer.model.js';

/** A Garba event (docs/events/event-management.md). Date/times are India Standard Time. */
@Table({ tableName: 'events' })
export class Event extends Model<InferAttributes<Event>, InferCreationAttributes<Event>> {
  @Column({ type: DataType.UUID, primaryKey: true, defaultValue: DataType.UUIDV4 })
  override id!: CreationOptional<string>;

  /** Public URL identifier, fixed at creation (renaming never breaks shared links). */
  @Column({ type: DataType.STRING(140), allowNull: false, unique: 'events_slug_unique' })
  slug!: string;

  @Column({ type: DataType.STRING(120), allowNull: false })
  name!: string;

  @Column({ type: DataType.TEXT, allowNull: false })
  description!: string;

  @ForeignKey(() => EventOrganizer)
  @Column({ type: DataType.UUID, allowNull: false })
  organizerId!: string;

  @ForeignKey(() => City)
  @Column({ type: DataType.UUID, allowNull: false })
  cityId!: string;

  @ForeignKey(() => Area)
  @Column({ type: DataType.UUID, allowNull: true })
  areaId!: CreationOptional<string | null>;

  @Column({ type: DataType.STRING(150), allowNull: false })
  venueName!: string;

  @Column({ type: DataType.STRING(300), allowNull: false })
  venueAddress!: string;

  /** `YYYY-MM-DD` (IST). */
  @Column({ type: DataType.DATEONLY, allowNull: false })
  eventDate!: string;

  /** `HH:MM:SS` from the database; accepts `HH:MM`. */
  @Column({ type: DataType.TIME, allowNull: false })
  startTime!: string;

  @Column({ type: DataType.TIME, allowNull: false })
  endTime!: string;

  /**
   * GENERATED by the database from date + start time (IST). Never write it. `allowNull: true`
   * only skips Sequelize's own not-null check on insert; the column is NOT NULL in the database.
   */
  @Column({ type: DataType.DATE, allowNull: true })
  startsAt!: CreationOptional<Date>;

  /** GENERATED by the database (next day when end time < start time). Never write it. */
  @Column({ type: DataType.DATE, allowNull: true })
  endsAt!: CreationOptional<Date>;

  @Column({ type: DataType.STRING(255), allowNull: true })
  imagePublicId!: CreationOptional<string | null>;

  @Column({ type: DataType.STRING(500), allowNull: true })
  ticketUrl!: CreationOptional<string | null>;

  /** Pass price in paise when passes are sold on the platform (docs/payments/payment-flow.md). */
  @Column({ type: DataType.INTEGER, allowNull: true })
  passPricePaise!: CreationOptional<number | null>;

  /** Maximum passes sold (null = unlimited). */
  @Column({ type: DataType.INTEGER, allowNull: true })
  passCapacity!: CreationOptional<number | null>;

  @Column({
    type: DataType.STRING(20),
    allowNull: false,
    defaultValue: 'draft',
    validate: { isIn: [[...EVENT_STATUSES]] },
  })
  status!: CreationOptional<EventStatus>;

  @Column({ type: DataType.BOOLEAN, allowNull: false, defaultValue: false })
  isVerified!: CreationOptional<boolean>;

  @Column({ type: DataType.DATE, allowNull: true })
  verifiedAt!: CreationOptional<Date | null>;

  @Column({ type: DataType.DATE, allowNull: true })
  publishedAt!: CreationOptional<Date | null>;

  @Column({ type: DataType.DATE, allowNull: true })
  firstPublishedAt!: CreationOptional<Date | null>;

  @Column({ type: DataType.DATE, allowNull: true })
  archivedAt!: CreationOptional<Date | null>;

  @ForeignKey(() => AdminUser)
  @Column({ type: DataType.UUID, allowNull: false })
  createdByAdminId!: string;

  @ForeignKey(() => AdminUser)
  @Column({ type: DataType.UUID, allowNull: false })
  updatedByAdminId!: string;

  @CreatedAt
  override createdAt!: CreationOptional<Date>;

  @UpdatedAt
  override updatedAt!: CreationOptional<Date>;

  @BelongsTo(() => EventOrganizer, { foreignKey: 'organizerId' })
  organizer?: NonAttribute<EventOrganizer>;

  @BelongsTo(() => City, { foreignKey: 'cityId' })
  city?: NonAttribute<City>;

  @BelongsTo(() => Area, { foreignKey: 'areaId' })
  area?: NonAttribute<Area | null>;

  @BelongsTo(() => AdminUser, { foreignKey: 'createdByAdminId', as: 'createdBy' })
  createdBy?: NonAttribute<AdminUser>;

  @BelongsTo(() => AdminUser, { foreignKey: 'updatedByAdminId', as: 'updatedBy' })
  updatedBy?: NonAttribute<AdminUser>;
}
